# Generated by Django 4.2.16 on 2026-03-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='chat_message',
        ),
    ]
