# Generated by Django 6.0.3 on 2026-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classrooms_classroom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('note', 'Note')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('video_url', models.URLField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='Chapter / unit label for grouping, e.g. "Unit 1 — Algebra"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classrooms_coursecontent',
                'ordering': ['unit', 'created_at'],
            },
        ),
    ]
