# Generated by Django 4.2.16 on 2026-03-24 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='joined_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='unit',
            field=models.CharField(blank=True, help_text='Chapter / unit label for grouping, e.g. "Unit 1 — Algebra"', max_length=100),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms_classroom',
        ),
        migrations.AlterModelTable(
            name='coursecontent',
            table='classrooms_coursecontent',
        ),
    ]
