# Generated by Django 4.2.16 on 2026-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_active',
        ),
    ]
