# Generated by Django 4.2.16 on 2026-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_classroom_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_active',
        ),
    ]
