# Generated by Django 4.2.7 on 2026-04-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_classroom_is_active'),
        ('classrooms', '0004_remove_classroom_is_active'),
    ]

    operations = [
    ]
