# Generated by Django 6.0.3 on 2026-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_testimonial_email_alter_testimonial_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
