# Generated by Django 4.2.16 on 2026-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_seen'),
        ('accounts', '0007_user_must_change_password'),
        ('accounts', '0009_alter_testimonial_options_and_more'),
    ]

    operations = [
    ]
