# Generated by Django 4.2.16 on 2026-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260402_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
