# Generated by Django 4.2.7 on 2026-04-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_must_change_password'),
        ('accounts', '0011_remove_user_must_change_password_and_more'),
    ]

    operations = [
    ]
