# Generated by Django 4.2.16 on 2026-04-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_grades_seen_at'),
        ('accounts', '0011_remove_user_must_change_password_and_more'),
    ]

    operations = [
    ]
