# Generated by Django 4.2.29 on 2026-04-11 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260403_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[\\w.@+ -]+$', 'Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_/space characters.', 'invalid')]),
        ),
    ]
