# Generated by Django 6.0.3 on 2026-04-06 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('h3_course', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='global_concepts/pdfs/')),
                ('quiz', models.TextField(blank=True)),
                ('assignment', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'superadmin_globalconcept',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConceptVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='global_concepts/videos/')),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='superadmin.globalconcept')),
            ],
            options={
                'db_table': 'superadmin_globalconceptvideo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('language', models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('hindi', 'Hindi'), ('telugu', 'Telugu'), ('kannada', 'Kannada')], default='english', max_length=30)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('is_free', models.BooleanField(default=True)),
                ('has_certificate', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Unpublished'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_courses', to=settings.AUTH_USER_MODEL)),
                ('schools', models.ManyToManyField(blank=True, related_name='global_courses', to='superadmin.school')),
            ],
            options={
                'db_table': 'superadmin_globalcourse',
            },
        ),
        migrations.AddField(
            model_name='globalconcept',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='superadmin.globalcourse'),
        ),
        migrations.CreateModel(
            name='ConceptProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_progress', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='superadmin.globalconcept')),
            ],
            options={
                'db_table': 'superadmin_conceptprogress',
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='superadmin.globalcourse')),
            ],
            options={
                'db_table': 'superadmin_courseenrollment',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='classrooms.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='superadmin.globalcourse')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('classroom', 'course')},
            },
        ),
    ]
