# Generated by Django 5.2.12 on 2026-03-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalcourse',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='globalcourse',
            name='school',
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='global_courses', to='superadmin.school'),
        ),
        migrations.AlterField(
            model_name='globalcourse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterModelTable(
            name='globalcourse',
            table='superadmin_globalcourse',
        ),
        migrations.CreateModel(
            name='GlobalConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('h3_course', models.CharField(blank=True, max_length=200)),
                ('videos', models.FileField(blank=True, null=True, upload_to='global_concepts/videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='global_concepts/pdfs/')),
                ('quiz', models.TextField(blank=True, help_text='Quiz questions (text/JSON)')),
                ('assignment', models.TextField(blank=True, help_text='Assignment instructions')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='superadmin.globalcourse')),
            ],
            options={
                'db_table': 'superadmin_globalconcept',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
