# Generated by Django 5.2.12 on 2026-03-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_rename_content_globalcourse_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconcept',
            name='videos',
        ),
        migrations.AlterField(
            model_name='globalconcept',
            name='assignment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='globalconcept',
            name='quiz',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GlobalConceptVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='global_concepts/videos/')),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='superadmin.globalconcept')),
            ],
            options={
                'db_table': 'superadmin_globalconceptvideo',
                'ordering': ['order'],
            },
        ),
    ]
