# Generated by Django 5.2.12 on 2026-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_globalconcept_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconcept',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='has_certificate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('hindi', 'Hindi'), ('telugu', 'Telugu'), ('kannada', 'Kannada')], default='english', max_length=30),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalcourse',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
