# Generated by Django 4.2.16 on 2026-03-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_options_alter_classroom_students_and_more'),
        ('superadmin', '0005_courseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='classrooms.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='superadmin.globalcourse')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('classroom', 'course')},
            },
        ),
    ]
