# Generated by Django 6.0.3 on 2026-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_courseenrollment_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='deadline_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
