# Generated by Django 4.2.7 on 2026-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_courseenrollment_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
