# Generated by Django 4.2.7 on 2026-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_school_deadline_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
