# Generated by Django 4.2.16 on 2026-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcourse',
            name='status',
            field=models.CharField(choices=[('draft', 'Unpublished'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
