# Generated by Django 4.2.16 on 2026-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_alter_globalcourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
