# Generated by Django 4.2.7 on 2026-04-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_alter_globalcourse_status'),
        ('superadmin', '0011_alter_globalcourse_status'),
    ]

    operations = [
    ]
