# Generated by Django 4.2.7 on 2026-04-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_merge_20260403_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconcept',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
