# Generated by Django 4.2.7 on 2026-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_add_pdf_url_to_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconceptvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
