# Generated by Django 5.2.13 on 2026-04-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0014_globalconceptvideo_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconceptvideo",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
