# Generated by Django 5.2.13 on 2026-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0015_globalconceptvideo_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconceptvideo",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="global_concepts/video_covers/"
            ),
        ),
    ]
