# Generated by Django 4.2.16 on 2026-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submitted_at']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, help_text='Optional attachment (question paper, instructions, etc.)', null=True, upload_to='assignment_files/'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignments_assignment',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='assignments_submission',
        ),
    ]
